name: Question
description: Ask a question about kotlin-docs-kit.
title: "question: "
labels: ["question"]
body:
  - type: textarea
    id: question
    attributes:
      label: Your question
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context
      description: What have you tried? Which engine / package?
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Confirmation
      options:
        - label: I have searched existing issues.
          required: true
