import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));

// Typed view of the tokens icon map (name -> inner SVG markup), committed as
// src/theme/Icon/data.generated.ts because CI typechecks before any build.
// Regenerated on every preset build; `task ci` fails on drift.
const iconsJson = join(here, '..', '..', 'tokens', 'dist', 'icons.json');
const outFile = join(here, '..', 'src', 'theme', 'Icon', 'data.generated.ts');

if (!existsSync(iconsJson)) {
  console.error(
    `generate-icons: ${iconsJson} not found.\n` +
      'Build the tokens package first: `task tokens:build` (or `pnpm --filter @ktdocs/tokens build`).',
  );
  process.exit(1);
}

const icons = JSON.parse(await readFile(iconsJson, 'utf8'));
const entries = Object.entries(icons)
  .map(([name, markup]) => `  ${JSON.stringify(name)}: ${JSON.stringify(markup)},`)
  .join('\n');

const banner =
  '// GENERATED by scripts/generate-icons.mjs from @ktdocs/tokens dist/icons.json — do not edit.\n' +
  '// Lucide-derived icon set (ISC); source of truth: packages/tokens/src/icons/.\n';

await mkdir(dirname(outFile), { recursive: true });
await writeFile(
  outFile,
  `${banner}export const ICONS: Record<string, string> = {\n${entries}\n};\n`,
);
console.log(`generate-icons: ${Object.keys(icons).length} icons -> ${outFile}`);
