// Build the kit icon set from src/icons/*.svg (Lucide-derived, ISC) into:
//   dist/icons.json               — { name: innerSvgMarkup } for JS consumers
//   dist/kt-icons.generated.html  — Hugo return-partial with the same map
// Source contract (validated below, hard-fail like build-components.mjs):
// 24×24 viewBox, fill="none", stroke="currentColor", stroke-width 1.5.
// Legacy names used by shortcode/content call sites stay as aliases.

import { readFile, readdir, writeFile, mkdir } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const pkgRoot = resolve(here, '..');
const iconsDir = resolve(pkgRoot, 'src/icons');

// Legacy icon names (public shortcode/content API) → canonical source icon.
const ALIASES = {
  book: 'book-open',
  file: 'file-text',
};

const files = (await readdir(iconsDir)).filter((n) => n.endsWith('.svg')).sort();
if (files.length === 0) throw new Error('No SVG sources found in src/icons/.');

const icons = {};
const problems = [];

for (const file of files) {
  const name = file.replace(/\.svg$/, '');
  const text = await readFile(resolve(iconsDir, file), 'utf8');
  const match = text.match(/<svg([^>]*)>([\s\S]*)<\/svg>\s*$/);
  if (!match) {
    problems.push(`${file}: no <svg> element`);
    continue;
  }
  const [, attrs, body] = match;
  if (!/viewBox="0 0 24 24"/.test(attrs)) problems.push(`${file}: viewBox must be "0 0 24 24"`);
  if (!/fill="none"/.test(attrs)) problems.push(`${file}: root fill must be "none"`);
  if (!/stroke="currentColor"/.test(attrs)) problems.push(`${file}: stroke must be "currentColor"`);
  if (!/stroke-width="1\.5"/.test(attrs)) problems.push(`${file}: stroke-width must be 1.5`);
  const inner = body
    .split('\n')
    .map((l) => l.trim())
    .filter(Boolean)
    .join('');
  if (!inner) problems.push(`${file}: empty markup`);
  if (inner.includes('`')) problems.push(`${file}: backtick in markup breaks the Hugo partial`);
  const badFill = inner.match(/fill="(?!none|currentColor)[^"]*"/);
  if (badFill) problems.push(`${file}: inner fill must be none/currentColor (got ${badFill[0]})`);
  icons[name] = inner;
}

for (const [alias, target] of Object.entries(ALIASES)) {
  if (!icons[target]) problems.push(`alias ${alias}: target ${target}.svg missing`);
  else icons[alias] = icons[target];
}

if (problems.length) {
  throw new Error(`Icon sources invalid:\n  ${problems.join('\n  ')}`);
}

const sorted = Object.fromEntries(Object.entries(icons).sort(([a], [b]) => a.localeCompare(b)));

await mkdir(resolve(pkgRoot, 'dist'), { recursive: true });

await writeFile(resolve(pkgRoot, 'dist/icons.json'), JSON.stringify(sorted, null, 2) + '\n');

const dictEntries = Object.entries(sorted)
  .map(([name, markup]) => `  "${name}" \`${markup}\``)
  .join('\n');
const partial =
  '{{- /* GENERATED by @ktdocs/tokens scripts/build-icons.mjs — do not edit.\n' +
  '       Lucide-derived icon set (ISC). Returns a dict of icon name →\n' +
  '       inner SVG markup; kt-icon.html wraps it in the <svg> shell. */ -}}\n' +
  '{{- return (dict\n' +
  dictEntries +
  '\n) -}}\n';
await writeFile(resolve(pkgRoot, 'dist/kt-icons.generated.html'), partial);

console.log(
  `Built dist/icons.json + dist/kt-icons.generated.html from ${files.length} sources (+${Object.keys(ALIASES).length} aliases).`,
);
